#spirng使用一个全局配置文件******这是全局配置文件
#修改SpringBoot默认配置的默认值 SpringBoot在底层都给我们配置好了
#YAML YAML Ain't Markup Language 是一个标记语言 不是一个标记语言
#以数据为中心，比xml、json等更适合做配置文件

#YAML基本语法
##使用缩进表示层级关系
##缩进时只允许使用空格，而不允许使用TAB键
##缩进空格的数目不重要，只要相同的层级元素左侧对齐即可
##大小写敏感

#YAML支持三种数据结构(见廖雪峰的文章）
##对象：键值对的集合 K：空格 V，这个空格一定不能省略
##数组：一组按次序排列的值
##字面量：单个的不可再分的值 K： V 字符串不用加上引号，如果加上""，就会转义，如果''，不会转义
server:
  port: 8081

#person:
#  lastname: zhangsan
#  age: 19
#  boss: false
#  birth: 2011/01/01
#  maps: {k1: v1, k2: 12}
#  list:
#    -lisi
#    -zhangsan
#    -wangwu
#  dog:
#    name: xiaogou
#    age: 3
